# Generated by Django 4.1.7 on 2023-05-10 10:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_remove_textmessage_unique appversion_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='textmessage',
            unique_together={('text', 'datetime', 'sender', 'receiver')},
        ),
    ]
