# Generated by Django 4.1.7 on 2023-05-10 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_textmessage_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='textmessage',
            unique_together=set(),
        ),
    ]
